### ISSUE TITLE
这个算法到底写完了没有？怎么Predict?

### ISSUE THREAD

**Issue by GuoZiyangTYUST** [calmisential/TensorFlow2.0_SSD#2]

**Comment by yeyupiaoling** [comment]
这个不就是预测代码吗？？？
https://github.com/calmisential/TensorFlow2.0_SSD/blob/8372f2410fa1d3e73c011ca50750334b23055d11/test.py#L28

**Comment by GuoZiyangTYUST** [comment]
当时没多久就跑路了，忘了这茬事
